DROP TABLE IF EXISTS movies;

CREATE TABLE movies (
    title TEXT PRIMARY KEY,
    genre TEXT NOT NULL,
    year INT NOT NULL,
    duration INT NOT NULL,
    description TEXT NOT NULL
);

INSERT INTO movies VALUES('The Sweetheart Story','Romance','2006','110','Address office above father. Such federal hospital give dog forward free.');
INSERT INTO movies VALUES('The Song and Dance Spectacular','Musical','2007','106','Green imagine along others face difficult east.');
INSERT INTO movies VALUES('The Criminally Chic','Noir','1993','94','None least nor response summer body.');
INSERT INTO movies VALUES('Challenges of Surviving Life','Drama','2017','113','Off of between wear scene. Heavy contain shoulder talk nature behind account. Modern east kind fish interest.');
INSERT INTO movies VALUES('Intense Investigation','Crime','2011','120','Peace agree remain notice white. Service next statement partner administration worry catch. Best purpose arm management record nature.');
INSERT INTO movies VALUES('The Suspicious Minds','Noir','2016','103','Language main head learn degree. Stock stage family final behind system.');
INSERT INTO movies VALUES('Vendetta of Impact','Action','1989','111','Consumer woman between best. Worker political simply per me yard. Full water build technology how so raise.');
INSERT INTO movies VALUES('The Tug of War','Drama','2019','105','Discover form involve system citizen. Last tax at arm. Stay go call happy ok store.');
INSERT INTO movies VALUES('The Documented Truth','Documentary','1983','114','Budget beat movement more professor crime moment. Let summer everything sort approach hit.');
INSERT INTO movies VALUES('The Timeless Romance','Romance','1991','92','Rule person network south.');
INSERT INTO movies VALUES('The Heart of Tradition','Family','2010','96','Above check represent skill according right area thousand. Discuss result organization study.');
INSERT INTO movies VALUES('Inferno of Victory','Action','1970','120','Choose happen position building only. No stage although partner beautiful free. Stay plan above.');
INSERT INTO movies VALUES('The Puzzling Crime','Mystery','2014','103','Buy quickly life usually eight special base fly. Doctor special wish no west senior sea. Glass much on unit begin step watch.');
INSERT INTO movies VALUES('Caring For My Nephew','Animation','1980','103','Me whom note listen state interesting interesting standard.');
INSERT INTO movies VALUES('The Rodeo Rider','Western','1995','114','Her seven describe particularly figure road sure campaign.');
INSERT INTO movies VALUES('Deadly Force','Crime','2016','90','Degree prepare policy weight. Mouth little necessary expert or. Stay heavy own somebody.');
INSERT INTO movies VALUES('The Ultimate Terror','Horror','1980','100','Agree thousand forget certain bank technology hard night. Sign such likely pass lose child data social.');
INSERT INTO movies VALUES('The Wild West Showdowns','Western','2013','109','Answer become physical professor particular. Idea himself summer difficult son.');
INSERT INTO movies VALUES('The Night Stalker','Noir','2016','102','Tell hard would tell program affect catch. Purpose left health blue. Response so difference rate mean.');
INSERT INTO movies VALUES('Drawing With My Niece','Animation','1988','95','Tree practice group. Natural very hope try record.');
INSERT INTO movies VALUES('Mystery at the Masquerade','Mystery','2019','118','Arm wide just community. Opportunity only security explain.');
INSERT INTO movies VALUES('Quadruple Humiliation','Action','2016','102','Social heavy camera respond school bar TV keep. Especially note out key early suggest hand leave. Easy response positive increase space board traditional economic.');
INSERT INTO movies VALUES('Raw Emotions','Drama','1978','99','Military ability themselves around involve couple avoid. Reach dog stay Mrs impact can mind.');
INSERT INTO movies VALUES('A Closer Look','Documentary','1984','102','Guy campaign usually available support. Tax degree task scientist.');
INSERT INTO movies VALUES('Unsolved Mysteries','Crime','1972','96','Teacher area important catch there. Probably agreement walk degree type television.');
INSERT INTO movies VALUES('The Happily Ever After','Romance','2013','105','Crime tell house door yet area. Wrong say development two today process interview. It look finally control or scene. All your for ago form free hard.');
INSERT INTO movies VALUES('The Dangerous Dealings','Noir','2019','97','Yes child not. Country treatment Congress fund.');
INSERT INTO movies VALUES('Celebrating With My School','Animation','1977','96','Line which off want. Beyond thousand theory.');
INSERT INTO movies VALUES('Family Traditions','Family','1982','95','Member property including where difficult. Medical training prepare remain. Attack performance message kid ball quickly school.');
INSERT INTO movies VALUES('The Path to Progress','History','1982','107','Foreign yourself plan eye. Career debate catch note.');
INSERT INTO movies VALUES('The Valiant Heroes','War','1992','117','Will within pay list. Woman box oil ahead film fight Mr happy. Fine themselves time baby increase admit.');
INSERT INTO movies VALUES('Criminal Cover-Up','Crime','1996','98','Action plant out.');
INSERT INTO movies VALUES('Exposed: The Truth Behind','Documentary','1986','96','Water get budget page. Worry social mouth interest. Capital use protect smile southern evidence particular world.');
INSERT INTO movies VALUES('Nightmares Unfold','Horror','2000','114','Others investment direction involve happy morning just. Leave bring price hope discussion cell big risk. Reality ability probably west quality.');
INSERT INTO movies VALUES('A Window to the Past','History','1982','90','System they worry note task benefit. Girl quality question lose.');
INSERT INTO movies VALUES('The Great Wars','History','1981','110','Pretty writer television finally. Must free political run likely price call. Song who could car. Short picture run indicate after.');
INSERT INTO movies VALUES('The Noir Detective','Noir','2008','90','Wife race purpose senior peace customer rock together. Unit finally section teacher garden anyone. Until read back theory.');
INSERT INTO movies VALUES('Maximum Danger','Action','1994','90','Raise education those car husband network idea. Eat image know range really realize worry. General including difficult view show.');
INSERT INTO movies VALUES('The Extraterrestrial Expedition','Science Fiction','2012','119','Sometimes push peace serve likely buy. Along season bank campaign glass animal.');
INSERT INTO movies VALUES('The Rhythmic Dream','Musical','1979','103','Box not throw heart happen measure. Weight recently law behavior idea oil plant. Foreign crime campaign game stuff know.');
INSERT INTO movies VALUES('The Human Experience','Drama','1992','99','Building attack reveal line. Garden training few agreement conference. Various describe player boy list single position.');
INSERT INTO movies VALUES('The Technologic Dream','Science Fiction','1984','100','Style meeting recognize war beautiful service. Little month while drive year purpose charge.');
INSERT INTO movies VALUES('The Bounty Hunters','Western','1995','103','Hear two possible produce value six. Low billion card drop environmental health government. Against policy suddenly their long at.');
INSERT INTO movies VALUES('Flower Of Wonder','Animation','2010','107','Place himself wait spring industry learn avoid. Indicate since foot.');
INSERT INTO movies VALUES('Forgotten Traditions','Family','1971','97','Doctor claim report thousand along difficult figure. Front first body image. Article special arrive feeling me something who. Mr ability rise.');
INSERT INTO movies VALUES('The Wagon Train West','Western','1992','116','Power trouble growth fight hair can responsibility. Poor store phone pull home. Middle answer yes I practice central.');
INSERT INTO movies VALUES('Struggle and Strength','Drama','2002','110','Ok possible page catch once. Deep million plan real until. Short language lead surface production stop.');
INSERT INTO movies VALUES('The Time Capsule','History','1999','101','Democratic huge computer. Any piece rather.');
INSERT INTO movies VALUES('Vendetta Vendors','Crime','1979','113','Successful where worker place. Yes director well either religious happen commercial. Great commercial news.');
INSERT INTO movies VALUES('The Age of Empires','History','1993','120','Enter find study key really reflect. Suddenly short data charge. Base now sort crime my bit already attack.');
INSERT INTO movies VALUES('The Imaginary Realm','Fantasy','2005','116','With each seat really daughter. Listen least place serve force able.');
INSERT INTO movies VALUES('The Time-Space Continuum','Science Fiction','1973','105','Allow book Democrat mean cultural. Ahead they ask support girl seven. Section could them agency level break lose.');
INSERT INTO movies VALUES('The Love Affair','Romance','2018','118','Site among never vote identify. Especially amount market computer source kind. Rock door try.');
INSERT INTO movies VALUES('The Battle for Legacy','History','1985','116','Board serious remember team compare player. Personal about food west.');
INSERT INTO movies VALUES('Mystery Mayhem','Crime','2017','107','Employee early right source structure kind capital player. Late finish vote so no member.');
INSERT INTO movies VALUES('Humorous Hijinks','Comedy','2012','119','Father firm treatment across thousand big third. Stuff election everybody hold about figure month.');
INSERT INTO movies VALUES('The Lovebirds','Romance','1973','108','Day interview policy kitchen raise view middle. Recent born behavior myself center.');
INSERT INTO movies VALUES('The Shocking Turn of Events','Thriller','1993','114','Arm theory coach game. Old eye rate start industry set collection cultural.');
INSERT INTO movies VALUES('The Joy of Jokes','Comedy','1994','105','Task front party act friend. Situation home reason from record too himself.');
INSERT INTO movies VALUES('The Love of a Lifetime','Family','2016','105','Own exist participant try well go chair. Allow finish country wide security board use. Partner group necessary take once fall effect fight. Include star wish several often fight let.');
INSERT INTO movies VALUES('Tale Of Riddles','Animation','1993','111','Each eat individual issue serious. Military air moment quite city also.');
INSERT INTO movies VALUES('Laughter Land','Comedy','1996','93','Chance international difficult have century. We inside red best family. Mrs themselves several state particular rest agency.');
INSERT INTO movies VALUES('The Ties that Bind','Family','2006','116','Local increase trade cover. Staff budget a offer foot town. Prepare degree whom who.');
INSERT INTO movies VALUES('Foxes And Bears','Animation','2019','106','Gun threat trial. Seek suffer sport.');
INSERT INTO movies VALUES('Inner Turmoil','Drama','2000','95','Executive idea defense quality. White four score light possible.');
INSERT INTO movies VALUES('Life in Flux','Drama','2018','108','Deep process after project. Hand two their. Many fill spend whole foreign community find.');
INSERT INTO movies VALUES('The Dark Side of Fear','Horror','2000','90','Painting relationship today seem. Walk production author. Response song receive finish time national.');
INSERT INTO movies VALUES('The Enigma Factor','Mystery','1977','96','Attention eight me drive how weight political agreement. Might fund drive brother stand type husband. On each decide music maybe later beat attack.');
INSERT INTO movies VALUES('Untraceable Evidence','Crime','1979','119','Doctor carry social as. Charge building report.');
INSERT INTO movies VALUES('Real Stories','Documentary','2010','98','Business sound first police stage community a. Million range magazine or impact population. Both middle difference tough she put must.');
INSERT INTO movies VALUES('A Haunting Experience','Horror','1978','101','Number second save appear change number. Too might notice man.');
INSERT INTO movies VALUES('The Hidden Side','Documentary','1985','101','Whose there respond finally. Eight lay central.');
INSERT INTO movies VALUES('Thrilling Thievery','Crime','2003','119','Gas instead bed never. Still rise alone position product project Democrat. Appear if natural around travel write yes. Form become station state.');
INSERT INTO movies VALUES('The Bloody Battlefield','War','1976','116','Democratic experience food once. Build return leader indeed three decade.');
INSERT INTO movies VALUES('The Romantic Journey','Romance','2017','116','Nor open nothing attorney southern probably explain. Event provide boy safe member technology full.');
INSERT INTO movies VALUES('Controlling The Forest','Adventure','1984','103','Discuss fight edge value foot institution player. Face within resource bill.');
INSERT INTO movies VALUES('A Family Affair','Family','1993','110','Month else speech compare. Very both financial quite budget. Argue itself try show.');
INSERT INTO movies VALUES('The Scream Factory','Horror','1998','93','Protect leg instead. Book argue class wear protect rate leader. Wait listen fast specific field discover.');
INSERT INTO movies VALUES('In-Depth Insights','Documentary','1973','120','Six increase only note contain. As card measure common hand network. Country fund small entire.');
INSERT INTO movies VALUES('The Legacy of Love','Family','1992','105','Seven open away cost. First everyone hold somebody exactly. Two door site quickly.');
INSERT INTO movies VALUES('Duke of Revenge','Action','2019','100','Employee world news tree against. Measure exactly city national. Grow assume what son quality head support.');
INSERT INTO movies VALUES('The Sultry Side of Crime','Noir','2005','93','Need such test size. History either condition firm matter company life first.');
INSERT INTO movies VALUES('Deadly Consequence','Crime','1977','101','Commercial whose let. Stage establish cup pattern.');
INSERT INTO movies VALUES('The Circle of Life','Family','2006','101','Movement behind brother memory. Return bed husband discover father ever accept.');
INSERT INTO movies VALUES('A Match Made in Heaven','Romance','2007','101','How risk range skill tend imagine. Police save bag later from bit difficult. Race miss need lose crime relate personal. Week box girl into.');
INSERT INTO movies VALUES('Memories to Cherish','Family','1976','120','Series gas fine off. Almost news threat black.');
INSERT INTO movies VALUES('The Rise to Power','History','2009','108','Capital dog social improve thousand. Space throw girl enough.');
INSERT INTO movies VALUES('The Chronicles of History','History','2017','94','Drive election prevent can somebody recent body. Other matter decision since girl we student contain.');
INSERT INTO movies VALUES('The Power of Family','Family','1982','109','Themselves girl page pull sure agency. Heavy push once animal must top experience.');
INSERT INTO movies VALUES('The Cosmic Frontier','Science Fiction','2021','102','Seem age suffer. Also year remain. Reach east my everybody total gun.');
INSERT INTO movies VALUES('The Courageous Fight','War','1992','106','Why heavy develop war player reflect decade. Special girl of nor entire. Only decision what us parent support.');
INSERT INTO movies VALUES('Triumph Over Tragedy','Drama','1991','112','Policy cold simply understand analysis. Popular education safe professor. Story certainly Mrs right north very write. Especially need option fill.');
INSERT INTO movies VALUES('The Frontier Justice','Western','2003','116','Person magazine bed anyone require about task write. Account report character bar. East south level across.');
INSERT INTO movies VALUES('Unsolved Puzzler','Mystery','1975','95','Thus unit adult common least peace become. Big to opportunity act reflect seven around.');
INSERT INTO movies VALUES('The Shadow of Evil','Crime','1997','108','Garden what bed fast hand garden. With which plan cost. Parent bring picture cell talk officer quickly stock.');
INSERT INTO movies VALUES('Intense Interactions','Drama','1979','118','Environmental person avoid quality event huge financial TV.');
INSERT INTO movies VALUES('The Space Odyssey','Science Fiction','1980','116','Heavy walk past. It would lay tonight. Pass one theory seven perform move along.');
INSERT INTO movies VALUES('The Timeless Tale','History','1971','111','Agent exist son step tree. Capital enjoy chance quite parent throw third. Remember weight tax process some law animal.');
INSERT INTO movies VALUES('The Horror Within','Horror','2018','117','Give little wait know adult. Believe often pretty card office beautiful.');
INSERT INTO movies VALUES('The Smoky Rooms','Noir','2012','96','Turn college someone senior beat painting. Unit sort past land. Play try product instead my.');
